management.endpoints.web.exposure.include=*
management.info.env.enabled=true

#Görülmesini istemedigimiz endpointsleri böyle engelleyebiliriz
management.endpoints.web.exposure.exclude=health,info


info.app.name=My super cool app
info.app.description=A crazy fun app
info.app.version=1.0.0

spring.security.user.name=Cemal
spring.security.user.password=0011.C


#Change Spring boot embedded server port. 8080 is default value.
server.port=7070

#
#Set the context path of the application
server.servlet.context-path=/mycoolapp